### ISSUE TITLE
Device attribute in NetworkRoutes ambiguous

### ISSUE THREAD

**Issue by nemesisdesign** [interop-dev/netjson#13]
sent by Thijs van Veen

> In the Route object, you suggest a Device field to reference the
> actual interface you're targeting.
> I suggest changing the name Device to Destination Interface or something
> similar to differentiate in terminology between devices (nodes) and
> their interfaces.

We forgot to address this.

**Comment by HRogge** [comment]
Not sure if this is really an issue, there is only one device per route which is relevant. Renaming it to something with "interface" could work, but I am not sure if "outgoing interface" or "destination interface" really makes that much sense for a routing entry.

**Comment by nemesisdesign** [comment]
During the battlemesh v8 we discussed this with other routing devs and they were fine with this, therefore I'm closing this issue.
