### ISSUE TITLE
Add a source interface field in NetworkRoutes

### ISSUE THREAD

**Issue by nemesisdesign** [interop-dev/netjson#14]
sent by Thijs van Veen

> You suggest a Source field for source-specific routing.
> I suggest adding a Source Interface field, this way (it seems to me) you
> can more easily handle multi-interface devices.
>
> In my experiences, multi-interface devices have always caused issues
> when trying to describe them and it would be great to take care of that
> issue in what is supposed to become a standard.

We forgot to address this

**Comment by HRogge** [comment]
I don't think routes have source-interface fields... source-prefix/IP, but not interface. You can simulate something like this with policy routing, but you can do all kind of crazy other stuff with policy routing.

I think we need feedback for this what is meant with a "source interface" field.

**Comment by nemesisdesign** [comment]
Closed because we have a source field which is enough for the moment.
