### ISSUE TITLE
Standardize node alias list

### ISSUE THREAD

**Issue by gabri94** [interop-dev/netjson#15]
A lot of routing protocols can have multiple IDs (aliases) for the same node.
In OLSR this is called MID, in batman-adv primary and secondary id.
We should find a standard way to rapresent it in the various json.

I propose to add this optional attribute inside of the elements of the list "nodes":
```javascript
"aliases": [
    "172.16.40.25",
    "172.16.40.26"
]
```

so "nodes" would become something like:
```javascript
"nodes": [
    {
        "id": "172.16.40.24",
        "aliases": [
            "172.16.40.25",
            "172.16.40.26"
        ],
        "label": "node-A",
        "properties": {
            "hostname": "node1.my.net"
        }
    }
]
```
See ML thread: https://lists.funkfeuer.at/pipermail/interop-dev/2015-June/000421.html

**Comment by nemesisdesign** [comment]
I sent that link to Antonio (ordex), batman-adv contributor, he told me he's confused by the naming of the issue, because batman-adv does not have secondary ids, just one id and secondary interfaces.

He also told me that before standardazing we should see if "alias" in other routing protocols have the same meaning.

**Comment by kostko** [comment]
In OLSR there are MIDs (identifiers used on all the interfaces where the OLSR is running, in addition to the router ID). In order to get "aliases" in Babel, you need to look at all the link-local addresses of all the interfaces where Babel is listening.

And yes, router id is something else. While in OLSR, router ID is just one of the IP addresses (so it looks the same as any "alias"), for example in Babel, the router ID is not even an IP address, while aliases are IPv6 link-local addresses. So IMO "alias" is a better term and there is always only one router ID.

**Comment by nemesisdesign** [comment]
Thanks @kostko :+1: 

Henning adds:

> Hi,
> 
> maybe it would be more clear to call the list "Local Addresses" ?
> 
> Its just a list of addresses (Mac/IP) which you can use to talk to this node.
> 
> Henning

**Comment by kostko** [comment]
Yeah, that makes even more sense. So either "aliases" or "local_addresses" (is this the proposed field name?) is fine with me.

**Comment by nemesisdesign** [comment]
`local_addresses` sounds good because it's explicit. So according to the discussion this would make sense on OLSR, batman-adv and babel, right?

**Comment by kostko** [comment]
Yes, they are either IPv4, IPv6 (L3 routing protocols) or MAC (L2 routing protocols) addresses. So I think `local_addresses` is good.

**Comment by NeoRaider** [comment]
In the "nodeinfo" format currently used by Gluon, we make a clear distinction between addresses "on top" of the batman-adv layer, and addresses on which batman-adv is running. In the latest Gluon release, we've also added some additional information about the "types" of the underlying interfaces ("wireless", "tunnel", and "other" for anything not detected as wireless or tunnel, so mostly wired connections), which we plan to use in topology visualizations.

Example of our current format:

```
{
  "network": {
    "mac": "XX:XX:XX:XX:XX:XX",
    "addresses": [
      "XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX",
      "fe80::XXXX:XXXX:XXXX:XXXX",
      ...
    ],  
    "mesh": {
      "bat0": {
        "interfaces": {
          "other": [
            "XX:XX:XX:XX:XX:XX",
            ...
          ],  
          "tunnel": [
            "XX:XX:XX:XX:XX:XX",
            ...
          ],  
          "wireless": [
            "XX:XX:XX:XX:XX:XX",
            ...
          ]   
        }   
      }   
    },  
    ... 
  },  
  ... 
}
```

`mac` is the address of the `bat0` interface, the addresses listed under `mesh/bat0/interfaces` belong to the interfaces batman-adv is meshing over.

The `addresses` section has nothing to do with meshing at all, this is just information about the addresses the node can be contacted over.

One of the addresses listed in other, tunnel or wireless is the so-called "primary" batman-adv addresses (at least in the old batman-adv upto 2013.4, I'm not sure if something has changed about that in more recent versions). We hide that fact on purpose as the existance of a "primary" address is a detail of the inner workings of batman-adv. We don't need that information for visualization, so we don't include it at all to have as little protocol-specific information as possible in our format.

**Comment by nemesisdesign** [comment]
so anyone against `local_addresses`?

**Comment by gabri94** [comment]
what does local addresses include? in the case of olsr, the HNA neworks will be listed as a local addresses? additional addresses on the mesh interfaces? i think that we shoud keep only the addresses listed in the routing protocol to avoid problem in the graph generation.

In the case of bmx6 or cjdns? are we going o use the hash id as identifier? can it have "aliases"?

**Comment by nemesisdesign** [comment]
@gabri94 we are proposing to rename `aliases` in `local_addresses` and keep the meaning unchanged.
But we should find a clear definition of this property.

What's a good definition in your opinion?

**Comment by nemesisdesign** [comment]
Henning on the mailing list wrote: "Its just a list of addresses (Mac/IP) which you can use to talk to this node."

**Comment by nemesisdesign** [comment]
The choice are `aliases` and `local_addresses`.

After a few weeks of thoughts I prefer `aliases` because is short and clear enough.

**Comment by HRogge** [comment]
Just as a comment, "Local Addresses" are not HNAs, because they are not prefixes.

My suggestion for HNAs would be this:
https://github.com/interop-dev/netjson/issues/10

**Comment by nemesisdesign** [comment]
Take a look at https://github.com/interop-dev/netjson/commit/db8fb24dae091c1a15b247a7e178aff97016a515 and let me know what you think.
I'll close this issue if no further comments are received.
