### ISSUE TITLE
Shall we add a "Goals" statement below each definition?

### ISSUE THREAD

**Issue by nemesisdesign** [interop-dev/netjson#16]
I believe adding a "Goals" statement under each definition (eg: `NetworkGraph`, `DeviceConfiguration`), will help us to focus our scope.

If we don't achieve some focus, we could keep spinning in a wheel trying to add more and more details, so the question, rather than **"should we add x"?** in my opinion should be **does adding x help us to reach our goal?**.

**Comment by aaronkaplan** [comment]
makes sense
