### ISSUE TITLE
NetworkGraph: human readable weight

### ISSUE THREAD

**Issue by nemesisdesign** [interop-dev/netjson#18]
Different protocols can use different metrics which might be converted to a different textual representation.

How to deal with this problem?

* an additional attribute with a textual representation for each link
* one attribute for the entire `NetworkGraph` object

A third option would be:
* delegate the interpretation to the consumer application and discuss this issue again when we have more implementations.

**Comment by HRogge** [comment]
One attribute for the entire graph does not work because each Link can have a different metric value.

"delegating it to consumer application" means that the visualizer code needs to know internals about the routing metric. That is BAD for generalized code.

**Comment by nemesisdesign** [comment]
https://github.com/interop-dev/netjson/commit/1ecadb07df1a71531aad1bb06983f2812d4ed21b should  close the issue, feel free to reopen and rediscuss if needed.
