### ISSUE TITLE
DeviceConfiguration: interface "type" should be more flexible

### ISSUE THREAD

**Issue by nemesisdesign** [interop-dev/netjson#27]
Quoting from here:
https://www.reddit.com/r/darknetplan/comments/3l6226/netjson_rfc_draft_0/

If you're considering wider applicability, some things that come to mind:
- "Strictly defining the types of interfaces"

**Comment by bittorf** [comment]
you say "we should not be so strict". can you please give some examples?

**Comment by nemesisdesign** [comment]
@bittorf the current RFC draf (not submitted yet), in the [Interface Objects section](http://netjson.org/rfc.html#rfc.section.5.5) says:

type	   string	possible values: "ethernet", "wireless", "bridge", "virtual" or "loopback"

maybe it would be better to write something like:

RECOMMENDED possible values for this field are: "ethernet", "wireless", "bridge", "virtual" or "loopback". Additional values MAY be allowed if needed.

@aaronkaplan I'm assuming I can keep improving the RFC anytime before submitting it.

**Comment by aaronkaplan** [comment]
On Sep 18, 2015, at 10:08 AM, Federico Capoano <notifications@github.com> wrote:

> @bittorf the current RFC draf (not submitted yet), in the Interface Objects section says:
> 
> type string possible values: "ethernet", "wireless", "bridge", "virtual" or "loopback"
> 
> maybe it would be better to write something like:
> 
> RECOMMENDED possible values for this field are: "ethernet", "wireless", "bridge", "virtual" or "loopback". Additional values MAY be allowed if needed.
> 
> @aaronkaplan I'm assuming I can keep improving the RFC anytime before submitting it.
> 

Yes, of course :)

**Comment by nemesisdesign** [comment]
a856ccd should do!

**Comment by nemesisdesign** [comment]
I assume a856ccd is ok, if not, reopen.
